name: CI

env:
  ELIXIR_VERSION: "1.17.0-otp-27"
  MIX_ENV: test
  OTP_VERSION: "27.0"

on:
  push:
    branches:
      - "**"

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ env.OTP_VERSION }}
          elixir-version: ${{ env.ELIXIR_VERSION }}
      - uses: actions/cache@v3
        with:
          path: deps
          key: ${{ runner.os }}-mix-v1-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-mix-v1-
      - uses: actions/cache@v3
        with:
          path: _build/test
          key: ${{ runner.os }}-test-build-v1
          restore-keys: |
            ${{ runner.os }}-test-build-v1
      - name: Install Dependencies
        run: mix do deps.get, deps.compile
      - name: Compile app
        run: mix compile --force --warnings-as-errors
      - name: Check format
        run: mix format --check-formatted
      - name: Credo
        run: mix credo --strict\
      - name: Hex Audit
        run: mix hex.audit
      - name: Run Tests
        run: mix test
